# Generated by Django 4.1.3 on 2024-05-21 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='event',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='seconds',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
